/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtrlFrmMemoria;
import Modelo.ModeloTablas;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author Equipo 1
 */
public class FrmMemoria extends javax.swing.JFrame {
    private CtrlFrmMemoria control;
    /**
     * Creates new form Memoria
     */
    public FrmMemoria() {
        initComponents();
        ModeloTablas modeloTablas = new ModeloTablas();
        modeloTablas.actualizarTablaProcesos(getTableProcesos(), Main.colaProcesos);
        modeloTablas.actualizarTablaAreasLibres(getTableEspaciosLibres(), Main.areasLibres);
        modeloTablas.actualizarTablaParticiones(getTableParticiones(), Main.particiones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableEspaciosLibres = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableParticiones = new javax.swing.JTable();
        BtnNext = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableProcesos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableEspaciosLibres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "#", "Localidad", "Tamaño", "Estado"
            }
        ));
        jScrollPane1.setViewportView(TableEspaciosLibres);

        TableParticiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Localidad", "Tamaño", "Estado", "Proceso"
            }
        ));
        jScrollPane2.setViewportView(TableParticiones);

        BtnNext.setText("Siguiente paso");
        BtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNextActionPerformed(evt);
            }
        });

        TableProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Proceso", "Tamaño", "Llegada", "Duración"
            }
        ));
        jScrollPane3.setViewportView(TableProcesos);

        jLabel1.setText("Tabla de procesos");

        jLabel2.setText("Tabla de areas libres");

        jLabel3.setText("Tabla de particiones");

        jLabel4.setText("Proceso MVT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(BtnNext)))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnNext)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNextActionPerformed
        control.siguientePaso();
    }//GEN-LAST:event_BtnNextActionPerformed

    public CtrlFrmMemoria getControl() {
        return control;
    }

    public void setControl(CtrlFrmMemoria control) {
        this.control = control;
    }

    public JButton getBtnNext() {
        return BtnNext;
    }

    public void setBtnNext(JButton BtnNext) {
        this.BtnNext = BtnNext;
    }

    public JTable getTableEspaciosLibres() {
        return TableEspaciosLibres;
    }

    public void setTableEspaciosLibres(JTable TableEspaciosLibres) {
        this.TableEspaciosLibres = TableEspaciosLibres;
    }

    public JTable getTableParticiones() {
        return TableParticiones;
    }

    public void setTableParticiones(JTable TableParticiones) {
        this.TableParticiones = TableParticiones;
    }

    public JTable getTableProcesos() {
        return TableProcesos;
    }

    public void setTableProcesos(JTable TableProcesos) {
        this.TableProcesos = TableProcesos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNext;
    private javax.swing.JTable TableEspaciosLibres;
    private javax.swing.JTable TableParticiones;
    private javax.swing.JTable TableProcesos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
