package com.sw.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.AbstractListModel;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTree;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ObjectProperty;

/**
 *
 * @author Nicolás
 */
public class Test extends javax.swing.JFrame
{

    /**
     * Creates new form test
     */
    public Test()
    {
        initComponents();

        JMenuItem menu = new JMenu("Opciones...");
        menu.add(new JMenuItem("Opción 1"));
        menu.add(new JMenuItem("Opción 2"));

        popup.add(menu);
        jDesktopPane1.setComponentPopupMenu(popup);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        bindingGroup = new BindingGroup();

        popup = new JPopupMenu();
        buttonGroup1 = new ButtonGroup();
        jDesktopPane1 = new JDesktopPane();
        jSplitPane2 = new JSplitPane();
        jTabbedPane1 = new JTabbedPane();
        jPanel5 = new JPanel();
        jPanel9 = new JPanel();
        filler3 = new Box.Filler(new Dimension(0, 10), new Dimension(0, 10), new Dimension(32767, 10));
        jRadioButton1 = new JRadioButton();
        jRadioButton2 = new JRadioButton();
        jRadioButton3 = new JRadioButton();
        jRadioButton4 = new JRadioButton();
        jPanel6 = new JPanel();
        jSeparator1 = new JSeparator();
        jButton3 = new JButton();
        jPanel7 = new JPanel();
        jPanel10 = new JPanel();
        jScrollPane3 = new JScrollPane();
        jTable2 = new JTable();
        jPanel11 = new JPanel();
        jPanel8 = new JPanel();
        jButton4 = new JButton();
        jButton5 = new JButton();
        jScrollPane4 = new JScrollPane();
        jTree1 = new JTree();
        jPanel4 = new JPanel();
        internalFrame = new JInternalFrame();
        jPanel3 = new JPanel();
        jLabel2 = new JLabel();
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();
        jScrollPane2 = new JScrollPane();
        jList1 = new JList<>();
        jPanel1 = new JPanel();
        filler2 = new Box.Filler(new Dimension(0, 5), new Dimension(0, 5), new Dimension(32767, 5));
        jLabel1 = new JLabel();
        filler1 = new Box.Filler(new Dimension(0, 5), new Dimension(0, 5), new Dimension(32767, 5));
        jPanel2 = new JPanel();
        jButton1 = new JButton();
        jButton2 = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new Dimension(600, 500));

        jDesktopPane1.setBackground(new Color(240, 240, 240));
        jDesktopPane1.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        jDesktopPane1.setLayout(new BorderLayout());

        jTabbedPane1.setPreferredSize(new Dimension(130, 38));

        jPanel5.setLayout(new GridLayout(3, 1));

        jPanel9.setAlignmentX(0.5F);
        jPanel9.setMaximumSize(new Dimension(32767, 100));
        jPanel9.setMinimumSize(new Dimension(93, 100));
        jPanel9.setPreferredSize(new Dimension(93, 100));
        jPanel9.setLayout(new BoxLayout(jPanel9, BoxLayout.Y_AXIS));
        jPanel9.add(filler3);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.setHorizontalAlignment(SwingConstants.LEFT);
        jRadioButton1.setHorizontalTextPosition(SwingConstants.RIGHT);
        jPanel9.add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("jRadioButton2");
        jRadioButton2.setHorizontalAlignment(SwingConstants.LEFT);
        jRadioButton2.setHorizontalTextPosition(SwingConstants.RIGHT);
        jPanel9.add(jRadioButton2);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("jRadioButton3");
        jRadioButton3.setHorizontalAlignment(SwingConstants.LEFT);
        jRadioButton3.setHorizontalTextPosition(SwingConstants.RIGHT);
        jPanel9.add(jRadioButton3);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("jRadioButton4");
        jRadioButton4.setHorizontalAlignment(SwingConstants.LEFT);
        jRadioButton4.setHorizontalTextPosition(SwingConstants.RIGHT);
        jPanel9.add(jRadioButton4);

        jPanel5.add(jPanel9);

        jPanel6.setAlignmentX(0.5F);
        jPanel6.setLayout(new BoxLayout(jPanel6, BoxLayout.Y_AXIS));

        jSeparator1.setMaximumSize(new Dimension(32767, 10));
        jPanel6.add(jSeparator1);

        jButton3.setText("jButton3");
        jButton3.setAlignmentX(0.5F);
        jPanel6.add(jButton3);

        jPanel5.add(jPanel6);

        jTabbedPane1.addTab("tab1", jPanel5);

        jPanel7.setLayout(new BorderLayout());

        jPanel10.setLayout(new BoxLayout(jPanel10, BoxLayout.Y_AXIS));

        jScrollPane3.setMaximumSize(new Dimension(32767, 200));
        jScrollPane3.setMinimumSize(new Dimension(23, 200));
        jScrollPane3.setPreferredSize(new Dimension(452, 200));

        jTable2.setModel(new DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "A", "B", "C", "D"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel10.add(jScrollPane3);

        jPanel11.setBackground(new Color(255, 255, 255));
        jPanel11.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        jPanel10.add(jPanel11);

        jPanel7.add(jPanel10, BorderLayout.CENTER);

        jButton4.setText("Set");
        jPanel8.add(jButton4);

        jButton5.setText("Get");
        jPanel8.add(jButton5);

        jPanel7.add(jPanel8, BorderLayout.PAGE_END);

        jTabbedPane1.addTab("tab2", jPanel7);

        jScrollPane4.setViewportView(jTree1);

        jTabbedPane1.addTab("tab3", jScrollPane4);

        jSplitPane2.setLeftComponent(jTabbedPane1);

        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, popup, ObjectProperty.create(), jPanel4, BeanProperty.create("componentPopupMenu"));
        bindingGroup.addBinding(binding);

        jPanel4.setLayout(null);

        internalFrame.setIconifiable(true);
        internalFrame.setMaximizable(true);
        internalFrame.setResizable(true);
        internalFrame.setTitle("Test");
        internalFrame.setVisible(true);

        jPanel3.setLayout(new BoxLayout(jPanel3, BoxLayout.Y_AXIS));

        jLabel2.setText("Test");
        jLabel2.setAlignmentX(0.5F);
        jPanel3.add(jLabel2);

        jTable1.setModel(new DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);

        jList1.setModel(new AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jPanel3.add(jScrollPane2);

        internalFrame.getContentPane().add(jPanel3, BorderLayout.CENTER);

        jPanel4.add(internalFrame);
        internalFrame.setBounds(10, 10, 370, 230);

        jSplitPane2.setRightComponent(jPanel4);

        jDesktopPane1.add(jSplitPane2, BorderLayout.CENTER);

        getContentPane().add(jDesktopPane1, BorderLayout.CENTER);

        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        jPanel1.add(filler2);

        jLabel1.setText("Esta es una prueba");
        jLabel1.setAlignmentX(0.5F);
        jPanel1.add(jLabel1);
        jPanel1.add(filler1);

        jButton1.setText("Click me!");
        jButton1.setAlignmentX(0.5F);
        jPanel2.add(jButton1);

        jButton2.setText("Click me 2!");
        jPanel2.add(jButton2);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, BorderLayout.NORTH);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            Test vista = new Test();
            vista.setVisible(true);
            vista.setLocationRelativeTo(null);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup buttonGroup1;
    private Box.Filler filler1;
    private Box.Filler filler2;
    private Box.Filler filler3;
    private JInternalFrame internalFrame;
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton4;
    private JButton jButton5;
    private JDesktopPane jDesktopPane1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JList<String> jList1;
    private JPanel jPanel1;
    private JPanel jPanel10;
    private JPanel jPanel11;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanel7;
    private JPanel jPanel8;
    private JPanel jPanel9;
    private JRadioButton jRadioButton1;
    private JRadioButton jRadioButton2;
    private JRadioButton jRadioButton3;
    private JRadioButton jRadioButton4;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JScrollPane jScrollPane4;
    private JSeparator jSeparator1;
    private JSplitPane jSplitPane2;
    private JTabbedPane jTabbedPane1;
    private JTable jTable1;
    private JTable jTable2;
    private JTree jTree1;
    private JPopupMenu popup;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
