package com.sw.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicolás
 */
public class Vista extends JFrame
{

    /**
     * Creates new form NewJFrame
     */
    public Vista()
    {
        initLookAndFeel();
        initComponents();
    }

    private void initLookAndFeel()
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels())
                if ("Windows".equals(info.getName()))
                {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new JPanel();
        filler3 = new Box.Filler(new Dimension(0, 10), new Dimension(0, 10), new Dimension(32767, 10));
        btnSigMomento = new JButton();
        estado = new JLabel();
        filler5 = new Box.Filler(new Dimension(0, 10), new Dimension(0, 10), new Dimension(32767, 10));
        jPanel3 = new JPanel();
        jLabel2 = new JLabel();
        jScrollPane1 = new JScrollPane();
        tablaAreasLibres = new JTable();
        filler1 = new Box.Filler(new Dimension(0, 20), new Dimension(0, 20), new Dimension(32767, 20));
        jLabel3 = new JLabel();
        jScrollPane2 = new JScrollPane();
        tablaParticiones = new JTable();
        jPanel2 = new JPanel();
        filler4 = new Box.Filler(new Dimension(0, 10), new Dimension(0, 10), new Dimension(32767, 10));
        jLabel4 = new JLabel();
        jPanel4 = new JPanel();
        jScrollPane3 = new JScrollPane();
        tablaProcesos = new JTable();
        btnAdmProcesos = new JButton();
        jPanel5 = new JPanel();
        filler2 = new Box.Filler(new Dimension(15, 0), new Dimension(15, 0), new Dimension(15, 0));
        panelGrafico = new JPanel();
        jLabel5 = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(252, 252, 252));
        setMaximumSize(new Dimension(800, 600));
        setMinimumSize(new Dimension(800, 600));
        setPreferredSize(new Dimension(800, 600));
        addMouseListener(new MouseAdapter()
        {
            public void mouseClicked(MouseEvent evt)
            {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new Color(252, 252, 252));
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        jPanel1.add(filler3);

        btnSigMomento.setText("Siguiente paso");
        btnSigMomento.setToolTipText("");
        btnSigMomento.setAlignmentX(0.5F);
        btnSigMomento.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jPanel1.add(btnSigMomento);

        estado.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        estado.setAlignmentX(0.5F);
        jPanel1.add(estado);
        jPanel1.add(filler5);

        getContentPane().add(jPanel1, BorderLayout.PAGE_END);

        jPanel3.setBackground(new Color(252, 252, 252));
        jPanel3.setLayout(new BoxLayout(jPanel3, BoxLayout.Y_AXIS));

        jLabel2.setText("Tabla de áreas libres");
        jLabel2.setAlignmentX(0.5F);
        jPanel3.add(jLabel2);

        tablaAreasLibres.setBackground(new Color(252, 252, 252));
        tablaAreasLibres.setModel(new DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "No", "Localidad", "Tamaño", "Estado"
            }
        ));
        tablaAreasLibres.setGridColor(new Color(237, 237, 237));
        jScrollPane1.setViewportView(tablaAreasLibres);

        jPanel3.add(jScrollPane1);
        jPanel3.add(filler1);

        jLabel3.setText("Tabla de particiones");
        jLabel3.setAlignmentX(0.5F);
        jPanel3.add(jLabel3);

        jScrollPane2.setBackground(new Color(252, 252, 252));

        tablaParticiones.setBackground(new Color(252, 252, 252));
        tablaParticiones.setModel(new DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "No", "Localidad", "Tamaño", "Estado", "Proceso"
            }
        ));
        tablaParticiones.setGridColor(new Color(237, 237, 237));
        jScrollPane2.setViewportView(tablaParticiones);

        jPanel3.add(jScrollPane2);

        getContentPane().add(jPanel3, BorderLayout.CENTER);

        jPanel2.setBackground(new Color(252, 252, 252));
        jPanel2.setMaximumSize(new Dimension(450, 150));
        jPanel2.setMinimumSize(new Dimension(450, 150));
        jPanel2.setPreferredSize(new Dimension(450, 150));
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));
        jPanel2.add(filler4);

        jLabel4.setFont(new Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("SIMULACIÓN DE ASIGNACIÓN DE MEMORIA CON MVT");
        jLabel4.setAlignmentX(0.5F);
        jPanel2.add(jLabel4);

        jPanel4.setBackground(new Color(252, 252, 252));
        FlowLayout flowLayout1 = new FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        jPanel4.setLayout(flowLayout1);

        jScrollPane3.setMaximumSize(new Dimension(480, 110));
        jScrollPane3.setMinimumSize(new Dimension(480, 110));
        jScrollPane3.setPreferredSize(new Dimension(480, 110));

        tablaProcesos.setBackground(new Color(252, 252, 252));
        tablaProcesos.setModel(new DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Proceso", "Tamaño", "Tiempo de llegada", "Tiempo finaliza"
            }
        ));
        tablaProcesos.setGridColor(new Color(237, 237, 237));
        jScrollPane3.setViewportView(tablaProcesos);

        jPanel4.add(jScrollPane3);

        btnAdmProcesos.setText("<html><font size=-1><center>Administrar<p>procesos</center></html>");
        btnAdmProcesos.setAlignmentX(0.5F);
        btnAdmProcesos.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnAdmProcesos.setHorizontalTextPosition(SwingConstants.CENTER);
        jPanel4.add(btnAdmProcesos);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, BorderLayout.NORTH);

        jPanel5.setBackground(new Color(252, 252, 252));
        jPanel5.add(filler2);

        getContentPane().add(jPanel5, BorderLayout.WEST);

        panelGrafico.setBackground(new Color(252, 252, 252));
        panelGrafico.setMaximumSize(new Dimension(400, 114));
        panelGrafico.setMinimumSize(new Dimension(400, 114));
        panelGrafico.setPreferredSize(new Dimension(400, 114));
        panelGrafico.setLayout(new BoxLayout(panelGrafico, BoxLayout.Y_AXIS));

        jLabel5.setText("Representación gráfica");
        jLabel5.setAlignmentX(0.5F);
        panelGrafico.add(jLabel5);

        getContentPane().add(panelGrafico, BorderLayout.EAST);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(MouseEvent evt)//GEN-FIRST:event_formMouseClicked
    {//GEN-HEADEREND:event_formMouseClicked
        requestFocus();
    }//GEN-LAST:event_formMouseClicked

    public JPanel getPanelGrafico()
    {
        return panelGrafico;
    }

    public JButton getBtnSigMomento()
    {
        return btnSigMomento;
    }

    public JButton getBtnAdmProcesos()
    {
        return btnAdmProcesos;
    }

    public JTable getTablaAreasLibres()
    {
        return tablaAreasLibres;
    }

    public JTable getTablaParticiones()
    {
        return tablaParticiones;
    }

    public JTable getTablaProcesos()
    {
        return tablaProcesos;
    }

    public JLabel getEstado()
    {
        return estado;
    }

    public JFrame getFrame()
    {
        return this;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnAdmProcesos;
    private JButton btnSigMomento;
    private JLabel estado;
    private Box.Filler filler1;
    private Box.Filler filler2;
    private Box.Filler filler3;
    private Box.Filler filler4;
    private Box.Filler filler5;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JPanel panelGrafico;
    private JTable tablaAreasLibres;
    private JTable tablaParticiones;
    private JTable tablaProcesos;
    // End of variables declaration//GEN-END:variables
}
